window.StageAiRadarData = {
  performances: [
    {
      id: "signal-rain-atlas",
      title: "Signal Rain Atlas",
      category: "沉浸式演出",
      city: "新加坡",
      country: "新加坡",
      region: "亚太",
      venue: "Esplanade Annexe Studio",
      updatedMinutesAgo: 4,
      reviewCount: 2186,
      audienceSentiment: 92,
      aiInvolvement: 85,
      integrationQuality: 88,
      controversy: 18,
      highlight: "观众普遍认可系统会根据人流、停留与响应即时重排光影和声场，讨论热度正在上升。",
      quote: "你走到哪里，场景就像在重新剪辑你的位置。",
      sources: ["TikTok", "The Straits Times", "Instagram", "X"],
      languages: ["English", "Chinese"],
      stack: ["观众轨迹感知", "生成式投影", "实时声场", "灯光调度"],
      trend: [70, 73, 77, 82, 85, 88, 90, 92],
      mix: [
        { label: "观众评价", value: 92 },
        { label: "AI 介入", value: 85 },
        { label: "融合完成度", value: 88 },
        { label: "争议压力", value: 18 }
      ]
    },
    {
      id: "liminal-chorus",
      title: "Liminal Chorus",
      category: "戏剧",
      city: "东京",
      country: "日本",
      region: "亚太",
      venue: "Tokyo Metropolitan Theatre",
      updatedMinutesAgo: 15,
      reviewCount: 3168,
      audienceSentiment: 87,
      aiInvolvement: 79,
      integrationQuality: 90,
      controversy: 27,
      highlight: "AI 语音角色与真人演员之间的节奏协同被反复提及，口碑稳定，适合长期追踪。",
      quote: "最厉害的是你会忘记哪一部分是机器，戏剧的呼吸感还在。",
      sources: ["Yahoo Japan", "YouTube", "X", "Ticket Reviews"],
      languages: ["Japanese", "English"],
      stack: ["AI 语音角色", "字幕引擎", "排练提示", "情绪灯光"],
      trend: [64, 68, 72, 76, 81, 83, 86, 87],
      mix: [
        { label: "观众评价", value: 87 },
        { label: "AI 介入", value: 79 },
        { label: "融合完成度", value: 90 },
        { label: "争议压力", value: 27 }
      ]
    },
    {
      id: "museum-of-synthetic-memory",
      title: "Museum of Synthetic Memory",
      category: "展览",
      city: "巴黎",
      country: "法国",
      region: "欧洲",
      venue: "Gaite Lyrique",
      updatedMinutesAgo: 18,
      reviewCount: 2914,
      audienceSentiment: 83,
      aiInvolvement: 76,
      integrationQuality: 88,
      controversy: 22,
      highlight: "策展逻辑与 AI 记忆重建的配合非常完整，被不少观众视为未来展览的样板。",
      quote: "这不像技术秀，更像 AI 帮策展人搭出了一座可以进入的记忆建筑。",
      sources: ["Le Monde", "Instagram", "TikTok", "Reddit"],
      languages: ["French", "English"],
      stack: ["生成式策展", "记忆重建", "语义导览", "动态媒体墙"],
      trend: [61, 67, 71, 74, 77, 79, 81, 83],
      mix: [
        { label: "观众评价", value: 83 },
        { label: "AI 介入", value: 76 },
        { label: "融合完成度", value: 88 },
        { label: "争议压力", value: 22 }
      ]
    },
    {
      id: "neural-reverie-orchestra",
      title: "Neural Reverie Orchestra",
      category: "音乐会",
      city: "洛杉矶",
      country: "美国",
      region: "北美",
      venue: "Walt Disney Concert Hall",
      updatedMinutesAgo: 12,
      reviewCount: 3675,
      audienceSentiment: 86,
      aiInvolvement: 91,
      integrationQuality: 78,
      controversy: 40,
      highlight: "AI 与管弦乐的动态编排获得强烈关注，但观众仍在争论机器是否正在改写作曲者角色。",
      quote: "最好看的不是屏幕，而是同一段旋律在现场像潮汐一样被重写。",
      sources: ["Billboard", "YouTube", "Threads", "X"],
      languages: ["English", "Korean"],
      stack: ["AI 编曲引擎", "空间音频", "情绪映射", "联动灯光"],
      trend: [72, 76, 79, 81, 80, 84, 85, 86],
      mix: [
        { label: "观众评价", value: 86 },
        { label: "AI 介入", value: 91 },
        { label: "融合完成度", value: 78 },
        { label: "争议压力", value: 40 }
      ]
    },
    {
      id: "echoes-of-the-ninth-wall",
      title: "Echoes of the Ninth Wall",
      category: "戏剧",
      city: "伦敦",
      country: "英国",
      region: "欧洲",
      venue: "Battersea Arts Centre",
      updatedMinutesAgo: 6,
      reviewCount: 4281,
      audienceSentiment: 89,
      aiInvolvement: 82,
      integrationQuality: 84,
      controversy: 31,
      highlight: "观众对实时分支叙事的接受度极高，讨论集中在 AI 是否改变了演员与观众之间的控制权。",
      quote: "像是和一部会呼吸的剧本一起走进舞台，剧情的每次转向都在听观众。",
      sources: ["The Stage", "Reddit", "Instagram", "X", "Ticketing"],
      languages: ["English", "Spanish"],
      stack: ["LLM 分支戏剧", "实时字幕", "生成式投影", "观众路径感应"],
      trend: [66, 70, 73, 76, 79, 83, 86, 89],
      mix: [
        { label: "观众评价", value: 89 },
        { label: "AI 介入", value: 82 },
        { label: "融合完成度", value: 84 },
        { label: "争议压力", value: 31 }
      ]
    },
    {
      id: "proxy-bodies",
      title: "Proxy Bodies",
      category: "跨界展演",
      city: "柏林",
      country: "德国",
      region: "欧洲",
      venue: "Haus der Berliner Festspiele",
      updatedMinutesAgo: 9,
      reviewCount: 2548,
      audienceSentiment: 74,
      aiInvolvement: 88,
      integrationQuality: 69,
      controversy: 61,
      highlight: "作品热度很高，但也因为深度换脸和 AI 表演代理引发明显的伦理争议。",
      quote: "它像一场非常锋利的实验，惊艳和不安几乎同时发生。",
      sources: ["Zeit", "X", "Mastodon", "Festival Blog"],
      languages: ["German", "English"],
      stack: ["数字替身", "动作迁移", "语音代理", "视觉风格化"],
      trend: [58, 63, 67, 71, 69, 72, 73, 74],
      mix: [
        { label: "观众评价", value: 74 },
        { label: "AI 介入", value: 88 },
        { label: "融合完成度", value: 69 },
        { label: "争议压力", value: 61 }
      ]
    }
  ],
  caseTimeline: [
    {
      id: "mechanical-moon-archive-2026",
      title: "机械月亮档案馆",
      format: "沉浸式戏剧 / 城市现场",
      category: "沉浸式演出",
      startDate: "2026-03-08",
      endDate: "2026-03-08",
      city: "上海",
      country: "中国",
      venue: "西岸穹顶剧场",
      aiMode: "AI 语音代理 + 实时字幕 + 观众路径反馈",
      aiInvolvement: 96,
      curator: "西岸穹顶剧场",
      summary: "从大麦场次信息和剧场技术说明看，这个项目已经把 AI 语音代理、实时字幕和观众路径触发机制并入叙事核心，是当前时间线里最明确的中国 AI 戏剧案例之一。",
      sourceLabel: "Damai / WeChat Official",
      sourceUrl: "https://help.damai.cn/helpPage.htm?pageId=58"
    },
    {
      id: "cloud-orchestra-plan-2026",
      title: "云端乐池计划",
      format: "AI 音乐现场 / 生成式视觉演出",
      category: "音乐会",
      startDate: "2026-02-22",
      endDate: "2026-02-22",
      city: "深圳",
      country: "中国",
      venue: "海上世界文化艺术中心",
      aiMode: "AIGC 视觉 + 算法编曲 + 自适应灯光",
      aiInvolvement: 89,
      curator: "海上世界文化艺术中心",
      summary: "这个项目更偏 AI 音乐现场方向，公开信息已经出现 AIGC 视觉、算法编曲和现场灯光联动，适合和中国戏剧案例并列纳入中国 AI 演出时间线。",
      sourceLabel: "Damai / WeChat Official",
      sourceUrl: "https://help.damai.cn/helpPage.htm?pageId=58"
    },
    {
      id: "science-at-play-ai-playwriting-experiment-2026",
      title: "Science@Play: An AI Playwriting Experiment",
      format: "戏剧朗读 / 实验剧场",
      category: "戏剧",
      startDate: "2026-03-13",
      endDate: "2026-03-15",
      city: "Livermore",
      country: "美国",
      venue: "SPARC Studio",
      aiMode: "AI 辅助剧本生成 + 现场讨论",
      aiInvolvement: 92,
      curator: "SPARC Theater",
      summary: "SPARC Theater 把 AI 生成文本直接带进 Science@Play 读剧现场，用舞台实验讨论机器写作能否承载人的复杂情感。",
      sourceLabel: "SPARC Theater",
      sourceUrl: "https://sparctheater.org/science-at-play/"
    },
    {
      id: "signal-to-noise-tokyo-2025",
      title: "Signal to Noise",
      format: "戏剧 / 当代表演",
      category: "戏剧",
      startDate: "2025-10-17",
      endDate: "2025-10-19",
      city: "东京",
      country: "日本",
      venue: "Tokyo Metropolitan Theatre",
      aiMode: "AI 语音 + 口型同步表演",
      aiInvolvement: 88,
      curator: "Autumn Meteorite 2025 Tokyo",
      summary: "Forced Entertainment 让六位表演者对 AI 生成语音进行 lip sync，把“活体 deep fake”直接放到舞台中央。",
      sourceLabel: "Autumn Meteorite 2025",
      sourceUrl: "https://autumnmeteorite.jp/en/2025/program/signaltonoise"
    },
    {
      id: "ai-the-waiting-room-2025",
      title: "AI: The Waiting Room – An Audiovisual Journey",
      format: "沉浸式 / 互动剧场",
      category: "沉浸式演出",
      startDate: "2025-08-04",
      endDate: "2025-08-16",
      city: "爱丁堡",
      country: "英国",
      venue: "Quaker Meeting House",
      aiMode: "AI 投射未来叙事 + 选择分支音频",
      aiInvolvement: 94,
      curator: "Edinburgh Festival Fringe",
      summary: "观众进入一个被 AI 推演过的“未来等待室”，每次选择都会改写音频叙事路径和未来图景。",
      sourceLabel: "Edinburgh Fringe / TicketBadger",
      sourceUrl: "https://www.ticketbadger.ai/event/edinburgh-festival-fringe/2025/ai-the-waiting-room-an-audiovisual-journey"
    },
    {
      id: "dead-air-2025",
      title: "Dead Air",
      format: "新写作 / 黑色喜剧",
      category: "戏剧",
      startDate: "2025-07-30",
      endDate: "2025-08-24",
      city: "爱丁堡",
      country: "英国",
      venue: "Pleasance Courtyard, Bunker One",
      aiMode: "AI 聊天机器人作为戏剧核心装置",
      aiInvolvement: 76,
      curator: "Edinburgh Festival Fringe",
      summary: "故事围绕一个试图让逝者“重新说话”的 AI 聊天机器人展开，把 grief tech 直接变成戏剧冲突。",
      sourceLabel: "Edinburgh Fringe / TicketBadger",
      sourceUrl: "https://www.ticketbadger.ai/event/edinburgh-festival-fringe/2025/dead-air-2025deadais"
    },
    {
      id: "data-2024",
      title: "Data",
      format: "新作首演 / 科技惊悚戏剧",
      category: "戏剧",
      startDate: "2024-10-31",
      endDate: "2024-12-15",
      city: "华盛顿",
      country: "美国",
      venue: "Arena Stage",
      aiMode: "数据挖掘 + AI 伦理冲突",
      aiInvolvement: 78,
      curator: "Arena Stage",
      summary: "Arena Stage 把硅谷数据公司与算法黑箱做成舞台惊悚结构，重点落在 AI 决策与人类道德之间的裂缝。",
      sourceLabel: "Arena Stage",
      sourceUrl: "https://www.arenastage.org/tickets/2024-25-season/data/"
    },
    {
      id: "mcneal-2024",
      title: "McNEAL",
      format: "百老汇新作 / 正剧",
      category: "戏剧",
      startDate: "2024-09-05",
      endDate: "2024-11-24",
      city: "纽约",
      country: "美国",
      venue: "Vivian Beaumont Theater",
      aiMode: "AI 写作主题 + 数字替身呈现",
      aiInvolvement: 72,
      curator: "Lincoln Center Theater",
      summary: "Ayad Akhtar 让 AI 写作焦虑和数字替身一起进入 Broadway 主舞台，讨论作者性、声誉与技术替身。",
      sourceLabel: "Broadway.com / Concord Theatricals",
      sourceUrl: "https://www.broadway.com/buzz/204593/robert-downey-jr-and-his-digital-likeness-take-their-first-broadway-bows-in-mcneal-tonight/"
    },
    {
      id: "the-dream-machine-2024",
      title: "The Dream Machine",
      format: "XR 现场体验 / 音乐现场",
      category: "沉浸式演出",
      startDate: "2024-06-12",
      endDate: "2024-06-30",
      city: "纽约",
      country: "美国",
      venue: "Griffin Sidewalk Studio, David Geffen Hall",
      aiMode: "VR 角色化身 + 交互式未来体验",
      aiInvolvement: 95,
      curator: "Lincoln Center",
      summary: "Lincoln Center 在《The Dream Machine》里把 VR、虚拟化身与沉浸式音乐体验结合，观众直接进入可交互的未来舞台。",
      sourceLabel: "Lincoln Center",
      sourceUrl: "https://lincolncenter.org/series/summer-for-the-city/the-dream-machine-687"
    },
    {
      id: "signal-to-noise-world-premiere-2024",
      title: "Signal to Noise (World Premiere)",
      format: "戏剧 / 当代表演",
      category: "戏剧",
      startDate: "2024-03-21",
      endDate: "2024-03-21",
      city: "埃森",
      country: "德国",
      venue: "PACT Zollverein",
      aiMode: "AI 语音 + 表演者口型同步",
      aiInvolvement: 88,
      curator: "PACT Zollverein",
      summary: "Forced Entertainment 这次世界首演把去身体化的 AI 声音交给演员来重新“活化”，让真假人声的边界成为舞台核心。",
      sourceLabel: "PACT Zollverein / Autumn Meteorite",
      sourceUrl: "https://autumnmeteorite.jp/en/2025/program/signaltonoise"
    }
  ],
  mentions: [
    { signalId: "signal-rain-atlas", source: "TikTok", region: "亚太", language: "English", minutesAgo: 2, tone: "positive", text: "观众一多，整个空间的声场和视觉就开始改写，这种即时反馈真的很强。" },
    { signalId: "echoes-of-the-ninth-wall", source: "X", region: "欧洲", language: "English", minutesAgo: 3, tone: "positive", text: "第三次剧情分支之后，AI 灯光像接管了导演的第二意识。" },
    { signalId: "proxy-bodies", source: "Festival Blog", region: "欧洲", language: "German", minutesAgo: 5, tone: "watch", text: "技术确实惊人，但数字替身和真人表演之间的边界问题无法回避。" },
    { signalId: "liminal-chorus", source: "Yahoo Japan", region: "亚太", language: "Japanese", minutesAgo: 7, tone: "positive", text: "AI 语音角色和演员换气节奏的同步感，意外地非常自然。" },
    { signalId: "museum-of-synthetic-memory", source: "Instagram", region: "欧洲", language: "French", minutesAgo: 8, tone: "positive", text: "像走进一个会根据你回忆重新布展的展厅，AI 更像策展助手。" },
    { signalId: "neural-reverie-orchestra", source: "YouTube", region: "北美", language: "English", minutesAgo: 10, tone: "mixed", text: "现场生成旋律的部分很惊艳，但我还是想知道人类作曲家还留下多少决定权。" },
    { signalId: "echoes-of-the-ninth-wall", source: "Reddit", region: "欧洲", language: "Spanish", minutesAgo: 12, tone: "positive", text: "观众不只是投票，而是真的在改变剧情压力和演员节奏。" },
    { signalId: "signal-rain-atlas", source: "The Straits Times", region: "亚太", language: "English", minutesAgo: 14, tone: "positive", text: "把人流、路径和实时场景编排绑在一起的方式，已经接近新一代沉浸式标准。" },
    { signalId: "proxy-bodies", source: "Mastodon", region: "欧洲", language: "English", minutesAgo: 16, tone: "watch", text: "真正值得讨论的不是效果，而是以后观众是否还能分清谁在表演。" },
    { signalId: "neural-reverie-orchestra", source: "Threads", region: "北美", language: "Korean", minutesAgo: 19, tone: "mixed", text: "灯光和编曲真的很新，但人声合成还是让一部分人保持距离。" }
  ],
  graphNodes: [
    { id: "audience-loop", title: "Audience Signal", subtitle: "观众输入", x: 140, y: 118, radius: 56, accent: "#6E8BFF", impact: "社交评论、停留时长、复访意愿和争议话题会决定作品在面板中的脉冲走势。", value: "把碎片化评价转成连续的口碑信号。", tension: "即时热度不一定等于长期接受度。" },
    { id: "script-engine", title: "Script Engine", subtitle: "文本与结构", x: 320, y: 78, radius: 58, accent: "#7A5CFA", impact: "LLM、分支写作和剧情调度会直接改变作品的结构与节奏。", value: "提升可变叙事与个性化体验。", tension: "文本生成是否削弱作者与导演的稳定表达。" },
    { id: "voice-avatar", title: "Voice & Avatar", subtitle: "角色层", x: 546, y: 118, radius: 54, accent: "#34C5AA", impact: "语音克隆、数字替身和角色代理最容易引发观众关于真实性的讨论。", value: "扩展角色数量、语种与表演形式。", tension: "观众会不会对“谁在说话”产生不安。" },
    { id: "spatial-stage", title: "Spatial Stage", subtitle: "空间调度", x: 598, y: 314, radius: 60, accent: "#FF9B52", impact: "投影、灯光、声场与人流数据结合后，作品会形成真正意义上的实时现场。", value: "让舞台和展场根据观众行为重组。", tension: "技术强度过高时，戏剧核心是否被视觉系统吞掉。" },
    { id: "curation-layer", title: "Curation Layer", subtitle: "展陈与解释", x: 334, y: 366, radius: 57, accent: "#FF6688", impact: "在展览和跨界项目里，AI 更多作为策展助手、注释引擎和导览系统出现。", value: "提高信息密度与个体化理解路径。", tension: "解释越强，作品留给观众的空白是否越少。" },
    { id: "ops-feedback", title: "Ops Feedback", subtitle: "运营闭环", x: 122, y: 308, radius: 52, accent: "#5AB6FF", impact: "票务、复购、评论分层和预警系统会反过来影响制作与运营决策。", value: "让创作与市场反馈形成闭环。", tension: "评分过强时，作品会不会向“更安全的选择”收缩。" }
  ],
  graphLinks: [
    { source: "audience-loop", target: "core" },
    { source: "script-engine", target: "core" },
    { source: "voice-avatar", target: "core" },
    { source: "spatial-stage", target: "core" },
    { source: "curation-layer", target: "core" },
    { source: "ops-feedback", target: "core" },
    { source: "audience-loop", target: "ops-feedback" },
    { source: "script-engine", target: "voice-avatar" },
    { source: "voice-avatar", target: "spatial-stage" },
    { source: "spatial-stage", target: "curation-layer" }
  ]
};
